# Generated by Django 5.0.9 on 2024-12-05 23:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
