# Generated by Django 5.0.10 on 2024-12-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_picture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/picturethumbnails/'),
        ),
    ]
