# Generated by Django 5.0.10 on 2024-12-22 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_picture_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
