# Generated by Django 5.0.10 on 2024-12-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_recipe_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail_transformed',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipethumbnails/transformed/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(upload_to='images/recipethumbnails/full'),
        ),
    ]
