# Generated by Django 5.0.10 on 2025-05-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_recipe_thumbnail_transformed_alter_recipe_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Please enter a valid email address.', 'unique': 'An account with this email address already exists.'}, max_length=254, unique=True),
        ),
    ]
