# Generated by Django 5.0.6 on 2024-06-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/videothumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
