name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # specify your Node.js version

    - name: Install Dependencies
      run: npm install
      working-directory: ./reed-family # Updated path

    - name: Build
      run: npm run build
      working-directory: ./reed-family # Updated path

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: reed-family/build  # Specify path to build folder
